"../files/bspwm/bspwmrc" = "~/.config/bspwm/bspwmrc"
"../files/sxhkd/sxhkdrc" = "~/.config/sxhkd/sxhkdrc"
"../files/polybar/config" = "~/.config/polybar/config"
"../files/xfce4/terminal/terminalrc" = "~/.config/xfce4/terminal/terminalrc"
"../files/zshrc" = "~/.zshrc" 
"../files/xinitrc" = "~/.xinitrc"
"../files/Xresources" = "~/.Xresources"
"../files/cyan-lambda.zsh-theme" = "~/.oh-my-zsh/themes/cyan-lambda.zsh-theme"
