"~/.config/bspwm/bspwmrc" = "../files/bspwm/bspwmrc"
"~/.config/sxhkd/sxhkdrc" = "../files/sxhkd/sxhkdrc"
"~/.config/polybar/config.ini" = "../files/polybar/config.ini"
"~/.config/xfce4/terminal/terminalrc" = "../files/xfce4/terminal/terminalrc"
"~/.zshrc" = "../files/zshrc"
"~/.xinitrc" = "../files/xinitrc"
"~/.Xresources" = "../files/Xresources"
"~/.oh-my-zsh/themes/cyan-lambda.zsh-theme" = "../files/cyan-lambda.zsh-theme"
"~/.themes/nngtk" = "../files/nngtk"
