#! /bin/sh

#sxhkd &
#compton -b -r 20 &
#lxqt-notificationd &
nitrogen --restore &
sudo systemctl start dhcpcd@enp2s0.service &
numlockx &
fcitx &

bspc monitor -d Λ Ξ Π Σ ζ Θ Ψ Ω δ β

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^1'

bspc config focused_border_color            "#71C2AF"
bspc config active_border_color             "#212121"
bspc config normal_border_color             "#204d53"
bspc config urgent_border_color             "#2F343A"
