export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export XDG_CONFIG_HOME="$HOME/.config"

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

sxhkd &
compton -b -r 20 &
polybar watch -r &
lxqt-notificationd &
exec bspwm
